// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

public final class Person {
  private Person() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BookInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string author = 3;</code>
     */
    java.lang.String getAuthor();
    /**
     * <code>string author = 3;</code>
     */
    com.google.protobuf.ByteString
        getAuthorBytes();
  }
  /**
   * Protobuf type {@code BookInfo}
   */
  public  static final class BookInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BookInfo)
      BookInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookInfo.newBuilder() to construct.
    private BookInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookInfo() {
      id_ = 0L;
      title_ = "";
      author_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_BookInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_BookInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.BookInfo.class, Person.BookInfo.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTHOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object author_;
    /**
     * <code>string author = 3;</code>
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <code>string author = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getAuthorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, author_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getAuthorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, author_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person.BookInfo)) {
        return super.equals(obj);
      }
      Person.BookInfo other = (Person.BookInfo) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && getAuthor()
          .equals(other.getAuthor());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person.BookInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.BookInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.BookInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.BookInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.BookInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.BookInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.BookInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.BookInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.BookInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Person.BookInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.BookInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.BookInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person.BookInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BookInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BookInfo)
        Person.BookInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_BookInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_BookInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.BookInfo.class, Person.BookInfo.Builder.class);
      }

      // Construct using Person.BookInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        title_ = "";

        author_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_BookInfo_descriptor;
      }

      public Person.BookInfo getDefaultInstanceForType() {
        return Person.BookInfo.getDefaultInstance();
      }

      public Person.BookInfo build() {
        Person.BookInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person.BookInfo buildPartial() {
        Person.BookInfo result = new Person.BookInfo(this);
        result.id_ = id_;
        result.title_ = title_;
        result.author_ = author_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.BookInfo) {
          return mergeFrom((Person.BookInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.BookInfo other) {
        if (other == Person.BookInfo.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.BookInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.BookInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object author_ = "";
      /**
       * <code>string author = 3;</code>
       */
      public java.lang.String getAuthor() {
        java.lang.Object ref = author_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string author = 3;</code>
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        java.lang.Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string author = 3;</code>
       */
      public Builder setAuthor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string author = 3;</code>
       */
      public Builder clearAuthor() {
        
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <code>string author = 3;</code>
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        author_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BookInfo)
    }

    // @@protoc_insertion_point(class_scope:BookInfo)
    private static final Person.BookInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person.BookInfo();
    }

    public static Person.BookInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookInfo>
        PARSER = new com.google.protobuf.AbstractParser<BookInfo>() {
      public BookInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookInfo> getParserForType() {
      return PARSER;
    }

    public Person.BookInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MyLibraryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyLibrary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    java.util.List<Person.BookInfo> 
        getBooksList();
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    Person.BookInfo getBooks(int index);
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    int getBooksCount();
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    java.util.List<? extends Person.BookInfoOrBuilder> 
        getBooksOrBuilderList();
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    Person.BookInfoOrBuilder getBooksOrBuilder(
        int index);

    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */
    int getKeysCount();
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */
    boolean containsKeys(
        java.lang.String key);
    /**
     * Use {@link #getKeysMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getKeys();
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getKeysMap();
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */

    java.lang.String getKeysOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */

    java.lang.String getKeysOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code MyLibrary}
   */
  public  static final class MyLibrary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyLibrary)
      MyLibraryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyLibrary.newBuilder() to construct.
    private MyLibrary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyLibrary() {
      id_ = 0L;
      name_ = "";
      books_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyLibrary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                books_ = new java.util.ArrayList<Person.BookInfo>();
                mutable_bitField0_ |= 0x00000004;
              }
              books_.add(
                  input.readMessage(Person.BookInfo.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                keys_ = com.google.protobuf.MapField.newMapField(
                    KeysDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              keys__ = input.readMessage(
                  KeysDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              keys_.getMutableMap().put(
                  keys__.getKey(), keys__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          books_ = java.util.Collections.unmodifiableList(books_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Person.internal_static_MyLibrary_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetKeys();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Person.internal_static_MyLibrary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Person.MyLibrary.class, Person.MyLibrary.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOKS_FIELD_NUMBER = 3;
    private java.util.List<Person.BookInfo> books_;
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    public java.util.List<Person.BookInfo> getBooksList() {
      return books_;
    }
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    public java.util.List<? extends Person.BookInfoOrBuilder> 
        getBooksOrBuilderList() {
      return books_;
    }
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    public Person.BookInfo getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated .BookInfo books = 3;</code>
     */
    public Person.BookInfoOrBuilder getBooksOrBuilder(
        int index) {
      return books_.get(index);
    }

    public static final int KEYS_FIELD_NUMBER = 4;
    private static final class KeysDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  Person.internal_static_MyLibrary_KeysEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> keys_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetKeys() {
      if (keys_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            KeysDefaultEntryHolder.defaultEntry);
      }
      return keys_;
    }

    public int getKeysCount() {
      return internalGetKeys().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */

    public boolean containsKeys(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetKeys().getMap().containsKey(key);
    }
    /**
     * Use {@link #getKeysMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getKeys() {
      return getKeysMap();
    }
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getKeysMap() {
      return internalGetKeys().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */

    public java.lang.String getKeysOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetKeys().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; keys = 4;</code>
     */

    public java.lang.String getKeysOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetKeys().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      for (int i = 0; i < books_.size(); i++) {
        output.writeMessage(3, books_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetKeys(),
          KeysDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      for (int i = 0; i < books_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, books_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetKeys().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        keys__ = KeysDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, keys__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Person.MyLibrary)) {
        return super.equals(obj);
      }
      Person.MyLibrary other = (Person.MyLibrary) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && getBooksList()
          .equals(other.getBooksList());
      result = result && internalGetKeys().equals(
          other.internalGetKeys());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getBooksCount() > 0) {
        hash = (37 * hash) + BOOKS_FIELD_NUMBER;
        hash = (53 * hash) + getBooksList().hashCode();
      }
      if (!internalGetKeys().getMap().isEmpty()) {
        hash = (37 * hash) + KEYS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetKeys().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Person.MyLibrary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.MyLibrary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.MyLibrary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.MyLibrary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.MyLibrary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Person.MyLibrary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Person.MyLibrary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.MyLibrary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.MyLibrary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Person.MyLibrary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Person.MyLibrary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Person.MyLibrary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Person.MyLibrary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyLibrary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyLibrary)
        Person.MyLibraryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Person.internal_static_MyLibrary_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetKeys();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableKeys();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Person.internal_static_MyLibrary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Person.MyLibrary.class, Person.MyLibrary.Builder.class);
      }

      // Construct using Person.MyLibrary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBooksFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          booksBuilder_.clear();
        }
        internalGetMutableKeys().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Person.internal_static_MyLibrary_descriptor;
      }

      public Person.MyLibrary getDefaultInstanceForType() {
        return Person.MyLibrary.getDefaultInstance();
      }

      public Person.MyLibrary build() {
        Person.MyLibrary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Person.MyLibrary buildPartial() {
        Person.MyLibrary result = new Person.MyLibrary(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (booksBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            books_ = java.util.Collections.unmodifiableList(books_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.books_ = books_;
        } else {
          result.books_ = booksBuilder_.build();
        }
        result.keys_ = internalGetKeys();
        result.keys_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Person.MyLibrary) {
          return mergeFrom((Person.MyLibrary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Person.MyLibrary other) {
        if (other == Person.MyLibrary.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (booksBuilder_ == null) {
          if (!other.books_.isEmpty()) {
            if (books_.isEmpty()) {
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBooksIsMutable();
              books_.addAll(other.books_);
            }
            onChanged();
          }
        } else {
          if (!other.books_.isEmpty()) {
            if (booksBuilder_.isEmpty()) {
              booksBuilder_.dispose();
              booksBuilder_ = null;
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000004);
              booksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBooksFieldBuilder() : null;
            } else {
              booksBuilder_.addAllMessages(other.books_);
            }
          }
        }
        internalGetMutableKeys().mergeFrom(
            other.internalGetKeys());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Person.MyLibrary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Person.MyLibrary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Person.BookInfo> books_ =
        java.util.Collections.emptyList();
      private void ensureBooksIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          books_ = new java.util.ArrayList<Person.BookInfo>(books_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Person.BookInfo, Person.BookInfo.Builder, Person.BookInfoOrBuilder> booksBuilder_;

      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public java.util.List<Person.BookInfo> getBooksList() {
        if (booksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(books_);
        } else {
          return booksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public int getBooksCount() {
        if (booksBuilder_ == null) {
          return books_.size();
        } else {
          return booksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Person.BookInfo getBooks(int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);
        } else {
          return booksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder setBooks(
          int index, Person.BookInfo value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.set(index, value);
          onChanged();
        } else {
          booksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder setBooks(
          int index, Person.BookInfo.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.set(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder addBooks(Person.BookInfo value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(value);
          onChanged();
        } else {
          booksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder addBooks(
          int index, Person.BookInfo value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(index, value);
          onChanged();
        } else {
          booksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder addBooks(
          Person.BookInfo.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder addBooks(
          int index, Person.BookInfo.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder addAllBooks(
          java.lang.Iterable<? extends Person.BookInfo> values) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, books_);
          onChanged();
        } else {
          booksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder clearBooks() {
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          booksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Builder removeBooks(int index) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.remove(index);
          onChanged();
        } else {
          booksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Person.BookInfo.Builder getBooksBuilder(
          int index) {
        return getBooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Person.BookInfoOrBuilder getBooksOrBuilder(
          int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);  } else {
          return booksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public java.util.List<? extends Person.BookInfoOrBuilder> 
           getBooksOrBuilderList() {
        if (booksBuilder_ != null) {
          return booksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(books_);
        }
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Person.BookInfo.Builder addBooksBuilder() {
        return getBooksFieldBuilder().addBuilder(
            Person.BookInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public Person.BookInfo.Builder addBooksBuilder(
          int index) {
        return getBooksFieldBuilder().addBuilder(
            index, Person.BookInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .BookInfo books = 3;</code>
       */
      public java.util.List<Person.BookInfo.Builder> 
           getBooksBuilderList() {
        return getBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Person.BookInfo, Person.BookInfo.Builder, Person.BookInfoOrBuilder> 
          getBooksFieldBuilder() {
        if (booksBuilder_ == null) {
          booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Person.BookInfo, Person.BookInfo.Builder, Person.BookInfoOrBuilder>(
                  books_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          books_ = null;
        }
        return booksBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> keys_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetKeys() {
        if (keys_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              KeysDefaultEntryHolder.defaultEntry);
        }
        return keys_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableKeys() {
        onChanged();;
        if (keys_ == null) {
          keys_ = com.google.protobuf.MapField.newMapField(
              KeysDefaultEntryHolder.defaultEntry);
        }
        if (!keys_.isMutable()) {
          keys_ = keys_.copy();
        }
        return keys_;
      }

      public int getKeysCount() {
        return internalGetKeys().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */

      public boolean containsKeys(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetKeys().getMap().containsKey(key);
      }
      /**
       * Use {@link #getKeysMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getKeys() {
        return getKeysMap();
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getKeysMap() {
        return internalGetKeys().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */

      public java.lang.String getKeysOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetKeys().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */

      public java.lang.String getKeysOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetKeys().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearKeys() {
        internalGetMutableKeys().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */

      public Builder removeKeys(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableKeys().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableKeys() {
        return internalGetMutableKeys().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */
      public Builder putKeys(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableKeys().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; keys = 4;</code>
       */

      public Builder putAllKeys(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableKeys().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyLibrary)
    }

    // @@protoc_insertion_point(class_scope:MyLibrary)
    private static final Person.MyLibrary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Person.MyLibrary();
    }

    public static Person.MyLibrary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyLibrary>
        PARSER = new com.google.protobuf.AbstractParser<MyLibrary>() {
      public MyLibrary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyLibrary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyLibrary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyLibrary> getParserForType() {
      return PARSER;
    }

    public Person.MyLibrary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BookInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BookInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyLibrary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyLibrary_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyLibrary_KeysEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyLibrary_KeysEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\"5\n\010BookInfo\022\n\n\002id\030\001 \001(\003\022\r" +
      "\n\005title\030\002 \001(\t\022\016\n\006author\030\003 \001(\t\"\220\001\n\tMyLibr" +
      "ary\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\030\n\005books\030\003" +
      " \003(\0132\t.BookInfo\022\"\n\004keys\030\004 \003(\0132\024.MyLibrar" +
      "y.KeysEntry\032+\n\tKeysEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BookInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BookInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BookInfo_descriptor,
        new java.lang.String[] { "Id", "Title", "Author", });
    internal_static_MyLibrary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_MyLibrary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyLibrary_descriptor,
        new java.lang.String[] { "Id", "Name", "Books", "Keys", });
    internal_static_MyLibrary_KeysEntry_descriptor =
      internal_static_MyLibrary_descriptor.getNestedTypes().get(0);
    internal_static_MyLibrary_KeysEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyLibrary_KeysEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
